<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

/**
 * Class DilTableSeeder
 * @package Database\Seeders
 */
class DilTableSeeder extends Seeder
{
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table("dil")->truncate();
        DB::table("dil")->insert([
            ["group" => "general", "key"=> "customer", "text" => "{'en':'Customer','tr':'Müşteri'}"],
            ["group" => "general", "key"=> "supplier", "text" => "{'en':'Supplier','tr':'Tedarikçi'}"],
            ["group" => "general", "key"=> "service", "text" => "{'en':'Service','tr':'Hizmet'}"],
            ["group" => "general", "key"=> "account", "text" => "{'en':'Account','tr':'Hesap'}"],
            ["group" => "general", "key"=> "product", "text" => "{'en':'Product','tr':'Ürün'}"],
            ["group" => "general", "key"=> "barcode", "text" => "{'en':'Barcode','tr':'Barkod'}"],
            ["group" => "general", "key"=> "code", "text" => "{'en':'Code','tr':'Kod'}"],
            ["group" => "general", "key"=> "unit", "text" => "{'en':'Unit','tr':'Birim'}"],
            ["group" => "general", "key"=> "new", "text" => "{'en':'New','tr':'Yeni'}"],
            ["group" => "general", "key"=> "old", "text" => "{'en':'Old','tr':'Eski'}"],
            ["group" => "general", "key"=> "offer", "text" => "{'en':'Offer','tr':'Teklif'}"],
            ["group" => "general", "key"=> "total", "text" => "{'en':'Total','tr':'Toplam'}"],
            ["group" => "general", "key"=> "status", "text" => "{'en':'Status','tr':'Durum'}"],
            ["group" => "general", "key"=> "company", "text" => "{'en':'Company','tr':'Şirket'}"],
            ["group" => "general", "key"=> "click", "text" => "{'en':'Click','tr':'Tıkla'}"],
            ["group" => "general", "key"=> "for", "text" => "{'en':'For','tr':'İçin'}"],
            ["group" => "general", "key"=> "validity", "text" => "{'en':'Validity','tr':'Geçerlilik'}"],
            ["group" => "general", "key"=> "detailed", "text" => "{'en':'Detailed','tr':'Detaylı'}"],
            ["group" => "general", "key"=> "price", "text" => "{'en':'Price','tr':'Fiyat'}"],
            ["group" => "general", "key"=> "amount", "text" => "{'en':'Amount','tr':'Tutar'}"],
            ["group" => "general", "key"=> "general", "text" => "{'en':'General','tr':'Genel'}"],
            ["group" => "general", "key"=> "print", "text" => "{'en':'Print','tr':'Yazdır'}"],
            ["group" => "general", "key"=> "printer", "text" => "{'en':'Printer','tr':'Yazıcı'}"],
            ["group" => "general", "key"=> "subTotal", "text" => "{'en':'Sub Total','tr':'Ara Toplam'}"],
            ["group" => "general", "key"=> "change", "text" => "{'en':'Change','tr':'Değiştirmek'}"],
            ["group" => "general", "key"=> "effective", "text" => "{'en':'Effective','tr':'Efektif'}"],
            ["group" => "general", "key"=> "order", "text" => "{'en':'Order','tr':'Sipariş'}"],
            ["group" => "general", "key"=> "phone", "text" => "{'en':'Phone','tr':'Telefon'}"],
            ["group" => "general", "key"=> "fax", "text" => "{'en':'fax','tr':'Faks'}"],
            ["group" => "general", "key"=> "number", "text" => "{'en':'Number','tr':'Numara'}"],
            ["group" => "general", "key"=> "sales", "text" => "{'en':'Sales','tr':'Satış'}"],
            ["group" => "general", "key"=> "purchase", "text" => "{'en':'Purchase','tr':'Alış'}"],
            ["group" => "general", "key"=> "remaining", "text" => "{'en':'Remaining','tr':'Kalan'}"],
            ["group" => "general", "key"=> "email", "text" => "{'en':'E-mail','tr':'E-posta'}"],
            ["group" => "general", "key"=> "address", "text" => "{'en':'Address','tr':'Adres'}"],
            ["group" => "general", "key"=> "abroad", "text" => "{'en':'Abroad','tr':'Yurt Dışı'}"],
            ["group" => "general", "key"=> "eBilling", "text" => "{'en':'E-Billing','tr':'E-Faturalama'}"],
            ["group" => "general", "key"=> "taxPayer", "text" => "{'en':'Taxpayer','tr':'Vergi Mükellefi'}"],
            ["group" => "general", "key"=> "tax", "text" => "{'en':'Tax','tr':'Vergi'}"],
            ["group" => "general", "key"=> "city", "text" => "{'en':'City','tr':'Şehir'}"],
            ["group" => "general", "key"=> "town", "text" => "{'en':'Town','tr':'Kasaba'}"],
            ["group" => "general", "key"=> "contact", "text" => "{'en':'Contact','tr':'İletişim'}"],
            ["group" => "general", "key"=> "current", "text" => "{'en':'Current','tr':'Cari'}"],
            ["group" => "general", "key"=> "name", "text" => "{'en':'Name','tr':'Ad'}"],
            ["group" => "general", "key"=> "surname", "text" => "{'en':'Surname','tr':'Soyad'}"],
            ["group" => "general", "key"=> "short", "text" => "{'en':'Short','tr':'Kısa'}"],
            ["group" => "general", "key"=> "save", "text" => "{'en':'Save','tr':'Kaydet'}"],
            ["group" => "general", "key"=> "back", "text" => "{'en':'Back','tr':'Geri'}"],
            ["group" => "general", "key"=> "description", "text" => "{'en':'Description','tr':'Açıklama'}"],
            ["group" => "general", "key"=> "edit", "text" => "{'en':'Edit','tr':'Düzenle'}"],
            ["group" => "general", "key"=> "date", "text" => "{'en':'Date','tr':'Tarih'}"],
            ["group" => "general", "key"=> "share", "text" => "{'en':'Share','tr':'Paylaş'}"],
            ["group" => "general", "key"=> "quantity", "text" => "{'en':'Quantity','tr':'Miktar'}"],
            ["group" => "general", "key"=> "collection", "text" => "{'en':'Collection','tr':'Tahsilat'}"],
            ["group" => "general", "key"=> "download", "text" => "{'en':'Download','tr':'İndir'}"],
            ["group" => "general", "key"=> "title", "text" => "{'en':'Title','tr':'Ünvan'}"],
            ["group" => "general", "key"=> "operation", "text" => "{'en':'Operation','tr':'İşlem'}"],
            ["group" => "general", "key"=> "operations", "text" => "{'en':'Operations','tr':'İşlemler'}"],
            ["group" => "general", "key"=> "open", "text" => "{'en':'Open','tr':'Açık'}"],
            ["group" => "general", "key"=> "opening", "text" => "{'en':'Opening','tr':'Açılış'}"],
            ["group" => "general", "key"=> "information", "text" => "{'en':'Information','tr':'Bilgi'}"],
            ["group" => "general", "key"=> "informations", "text" => "{'en':'Informations','tr':'Bilgiler'}"],
            ["group" => "general", "key"=> "type", "text" => "{'en':'Type','tr':'Tür'}"],
            ["group" => "general", "key"=> "sum", "text" => "{'en':'Sum','tr':'Meblağ'}"],
            ["group" => "general", "key"=> "extract", "text" => "{'en':'Extract','tr':'Ekstre'}"],
            ["group" => "general", "key"=> "search", "text" => "{'en':'Search','tr':'Arama'}"],
            ["group" => "general", "key"=> "approved", "text" => "{'en':'Approved','tr':'Onaylı'}"],
            ["group" => "general", "key"=> "rejected", "text" => "{'en':'Rejected','tr':'Reddedilen'}"],
            ["group" => "general", "key"=> "delivered", "text" => "{'en':'Delivered','tr':'Teslim Edildi'}"],
            ["group" => "general", "key"=> "completed", "text" => "{'en':'Completed','tr':'Tamamlandı'}"],
            ["group" => "general", "key"=> "claimed", "text" => "{'en':'Claimed','tr':'Talep Edildi'}"],
            ["group" => "general", "key"=> "shipped", "text" => "{'en':'Shipped','tr':'Nakliye Edildi'}"],
            ["group" => "general", "key"=> "shipping", "text" => "{'en':'Shipping','tr':'Nakliye'}"],
            ["group" => "general", "key"=> "add", "text" => "{'en':'Add','tr':'Ekle'}"],
            ["group" => "general", "key"=> "category", "text" => "{'en':'Category','tr':'Kategori'}"],
            ["group" => "general", "key"=> "detail", "text" => "{'en':'Detail','tr':'Detay'}"],
            ["group" => "general", "key"=> "choose", "text" => "{'en':'Choose','tr':'Seç'}"],
            ["group" => "general", "key"=> "shop", "text" => "{'en':'Shop','tr':'Mağaza'}"],
            ["group" => "general", "key"=> "stock", "text" => "{'en':'Stock','tr':'Stok'}"],
            ["group" => "general", "key"=> "currency", "text" => "{'en':'Currency','tr':'Döviz'}"],
            ["group" => "general", "key"=> "check", "text" => "{'en':'Check','tr':'Çek'}"],
            ["group" => "general", "key"=> "bank", "text" => "{'en':'Bank','tr':'Banka'}"],
            ["group" => "general", "key"=> "branch", "text" => "{'en':'Branch','tr':'Şube'}"],
            ["group" => "general", "key"=> "invoice", "text" => "{'en':'Invoice','tr':'Fatura'}"],
            ["group" => "general", "key"=> "processed", "text" => "{'en':'Processed','tr':'İşlenen'}"],
            ["group" => "general", "key"=> "all", "text" => "{'en':'All','tr':'Tüm'}"],
            ["group" => "general", "key"=> "and", "text" => "{'en':'And','tr':'Ve'}"],
            ["group" => "general", "key"=> "return", "text" => "{'en':'Return','tr':'Dön'}"],
            ["group" => "general", "key"=> "location", "text" => "{'en':'Location','tr':'Location'}"],
            ["group" => "general", "key"=> "cancel", "text" => "{'en':'Cancel','tr':'İptal Et'}"],
            ["group" => "general", "key"=> "expense", "text" => "{'en':'Expense','tr':'Gider'}"],
            ["group" => "general", "key"=> "expenses", "text" => "{'en':'Expenses','tr':'Giderler'}"],
            ["group" => "general", "key"=> "action", "text" => "{'en':'Action','tr':'Aksiyon'}"],
            ["group" => "general", "key"=> "paid", "text" => "{'en':'Paid','tr':'Ödenen'}"],
            ["group" => "general", "key"=> "transfer", "text" => "{'en':'Transfer','tr':'Transfer Et'}"],
            ["group" => "general", "key"=> "money", "text" => "{'en':'Money','tr':'Para'}"],
            ["group" => "general", "key"=> "entry", "text" => "{'en':'Entry','tr':'Giriş'}"],
            ["group" => "general", "key"=> "out", "text" => "{'en':'Out','tr':'Çıkış'}"],
            ["group" => "general", "key"=> "convert", "text" => "{'en':'Convert','tr':'Dönüştür'}"],
            ["group" => "general", "key"=> "payable", "text" => "{'en':'Payable','tr':'Ödenecek'}"],
            ["group" => "general", "key"=> "payment", "text" => "{'en':'Payable','tr':'Ödeme'}"],
            ["group" => "general", "key"=> "proforma", "text" => "{'en':'Proforma','tr':'Proforma'}"],
            ["group" => "general", "key"=> "excluding", "text" => "{'en':'Excluding','tr':'Hariç'}"],
            ["group" => "general", "key"=> "movement", "text" => "{'en':'Movement','tr':'Hareket'}"],
            ["group" => "general", "key"=> "key", "text" => "{'en':'Key','tr':'Anahtar'}"],
            ["group" => "general", "key"=> "password", "text" => "{'en':'Password','tr':'Şifre'}"],
            ["group" => "general", "key"=> "client", "text" => "{'en':'Client','tr':'İstemci'}"],
            ["group" => "general", "key"=> "secret", "text" => "{'en':'Secret','tr':'Sır'}"],
            ["group" => "general", "key"=> "user", "text" => "{'en':'User','tr':'Kullanıcı'}"],
            ["group" => "general", "key"=> "mobile", "text" => "{'en':'Mobile','tr':'Mobil'}"],
            ["group" => "general", "key"=> "language", "text" => "{'en':'Language','tr':'Dil'}"],
            ["group" => "general", "key"=> "access", "text" => "{'en':'Access','tr':'Erişim'}"],
            ["group" => "general", "key"=> "submit", "text" => "{'en':'Submit','tr':'Gönder'}"],
            ["group" => "general", "key"=> "no", "text" => "{'en':'No','tr':'Hayır'}"],
            ["group" => "general", "key"=> "yes", "text" => "{'en':'Yes','tr':'Evet'}"],
            ["group" => "general", "key"=> "okay", "text" => "{'en':'Okay','tr':'Tamam'}"],
            ["group" => "general", "key"=> "view", "text" => "{'en':'View','tr':'Görünüm'}"],
            ["group" => "general", "key"=> "full", "text" => "{'en':'Full','tr':'Tam'}"],
            ["group" => "general", "key"=> "permission", "text" => "{'en':'Permission','tr':'İzin'}"],
            ["group" => "general", "key"=> "permissions", "text" => "{'en':'Permissions','tr':'İzinler'}"],
            ["group" => "general", "key"=> "module", "text" => "{'en':'Module','tr':'Modül'}"],
            ["group" => "general", "key"=> "arrangement", "text" => "{'en':'Arrangement','tr':'Düzenleme'}"],
            ["group" => "general", "key"=> "receipt", "text" => "{'en':'Receipt','tr':'Fiş'}"],
            ["group" => "general", "key"=> "row", "text" => "{'en':'Row','tr':'Satır'}"],
            ["group" => "general", "key"=> "archive", "text" => "{'en':'Archive','tr':'Arşivle'}"],
            ["group" => "general", "key"=> "vat", "text" => "{'en':'VAT','tr':'KDV'}"],
            ["group" => "general", "key"=> "cost", "text" => "{'en':'Cost','tr':'Maliyet'}"],
            ["group" => "general", "key"=> "update", "text" => "{'en':'Update','tr':'Güncelle'}"],
            ["group" => "general", "key"=> "confirmation", "text" => "{'en':'Confirmation','tr':'Doğrulama'}"],
            ["group" => "general", "key"=> "group", "text" => "{'en':'Group','tr':'Grup'}"],
            ["group" => "general", "key"=> "settings", "text" => "{'en':'Settings','tr':'Ayarlar'}"],
            ["group" => "general", "key"=> "show", "text" => "{'en':'Show','tr':'Göster'}"],
            ["group" => "general", "key"=> "widget", "text" => "{'en':'Widget','tr':'Bileşen'}"],
            ["group" => "general", "key"=> "my", "text" => "{'en':'My','tr':'Benim'}"],
            ["group" => "general", "key"=> "template", "text" => "{'en':'Template','tr':'Şablon'}"],
            ["group" => "general", "key"=> "templates", "text" => "{'en':'Templates','tr':'Şablonlar'}"],
            ["group" => "general", "key"=> "planning", "text" => "{'en':'Planning','tr':'Planlama'}"],
            ["group" => "general", "key"=> "warehouse", "text" => "{'en':'Warehouse','tr':'Depo'}"],
            ["group" => "general", "key"=> "tag", "text" => "{'en':'Tag','tr':'Etiket'}"],
            ["group" => "general", "key"=> "tags", "text" => "{'en':'Tags','tr':'Etiketler'}"],
            ["group" => "general", "key"=> "app", "text" => "{'en':'App','tr':'Uygulama'}"],
            ["group" => "general", "key"=> "manager", "text" => "{'en':'Manager','tr':'Yönetici'}"],


        ]);
    }
}
